apiVersion: apps/v1
kind: Deployment # kubernetes resource kind we are creating
metadata:
  name: spring-boot-web-k8s-deployment
  labels:
    app: spring-boot-web-k8s
spec:
  replicas: 3 # number of replicas that will be created for this deployment
  selector:
    matchLabels:
      app: spring-boot-web-k8s
  template:
    metadata:
      labels:
        app: spring-boot-web-k8s
    spec:
      containers:
        - name: spring-boot-web-k8s
          image: ssamantr/spring-boot-web-k8s:latest
          ports:
            - containerPort: 8080 # the port that the container is running on in the cluster