---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-web-k8s-service
spec:
  selector:
    app: spring-boot-web-k8s
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080